refresh:
  fields:
    vin:
      selector:
        text:

request_location:
  fields:
    vin:
      selector:
        text:

flash_lights:
  fields:
    vin:
      selector:
        text:

honk_horn:
  fields:
    vin:
      selector:
        text:

open_sunroof:
  fields:
    vin:
      selector:
        text:

close_sunroof:
  fields:
    vin:
      selector:
        text:

set_charge_limit:
  fields:
    vin:
      selector:
        text:
    percent:
      required: true
      selector:
        number:
          min: 50
          max: 100
          step: 5
          unit_of_measurement: "%"

start_charging:
  fields:
    vin:
      selector:
        text:

stop_charging:
  fields:
    vin:
      selector:
        text:

start_ventilate:
  fields:
    vin:
      selector:
        text:

stop_ventilate:
  fields:
    vin:
      selector:
        text:

start_heaters:
  fields:
    vin:
      selector:
        text:
    heaters:
      required: true
      selector:
        select:
          multiple: true
          options:
            - value: "front_left_seat"
              label: "Front left seat"
            - value: "front_right_seat"
              label: "Front right seat"
            - value: "rear_left_seat"
              label: "Rear left seat"
            - value: "rear_right_seat"
              label: "Rear right seat"
            - value: "steering_wheel"
              label: "Steering wheel"
            - value: "defrost"
              label: "Windshield defrost"

stop_heaters:
  fields:
    vin:
      selector:
        text:
    heaters:
      required: true
      selector:
        select:
          multiple: true
          options:
            - value: "front_left_seat"
              label: "Front left seat"
            - value: "front_right_seat"
              label: "Front right seat"
            - value: "rear_left_seat"
              label: "Rear left seat"
            - value: "rear_right_seat"
              label: "Rear right seat"
            - value: "steering_wheel"
              label: "Steering wheel"
            - value: "defrost"
              label: "Windshield defrost"

lock_glovebox:
  fields:
    vin:
      selector:
        text:
    pin:
      required: true
      selector:
        text:

unlock_glovebox:
  fields:
    vin:
      selector:
        text:

start_conditioning:
  fields:
    vin:
      selector:
        text:
    temp:
      required: true
      selector:
        number:
          min: 16
          max: 28
          step: 1
          unit_of_measurement: "°C"

stop_conditioning:
  fields:
    vin:
      selector:
        text:

lock_door:
  fields:
    vin:
      selector:
        text:

unlock_door:
  fields:
    vin:
      selector:
        text:

authorize_sensitive_commands:
  fields:
    vin:
      selector:
        text:
    pin:
      required: true
      selector:
        text:
          type: password

lock_sensitive_commands:
  fields:
    vin:
      selector:
        text:
